<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container70vFxbS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container70vFxbS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container70vFxbS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container70vFxbS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container70vFxbS\App_KernelDevDebugContainer([
    'container.build_hash' => '70vFxbS',
    'container.build_id' => '07089100',
    'container.build_time' => 1745455687,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container70vFxbS');
